version = 0.1
[default.deploy.parameters]
stack_name = "web-scraping-stack"
#s3_bucket = "bk-price-prediction-data"
resolve_s3 = true
s3_prefix = "web-scraping-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []