AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: web_scraping_project
Resources:
  WebScrapingFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.lambda_handler
      Runtime: python3.9
      CodeUri: .
      MemorySize: 512
      Timeout: 300
      Policies:
      - AWSLambdaBasicExecutionRole
      Events:
        WebScrapingApi:
          Type: Api
          Properties:
            Path: /webscraping
            Method: post
